# Fixtures file for puppet_spec_helper in the task: rake spec
fixtures:
  symlinks:
    st2: "#{source_dir}"
  forge_modules:
    httpauth: "jamtur01/httpauth"
    stdlib: "puppetlabs/stdlib"
    staging: "puppet/staging"
    apt: "puppetlabs/apt"
    epel: "puppet/epel"
    concat: "puppetlabs/concat"
    sudo: "saz/sudo"
    python: "puppet/python"
    inifile: "puppetlabs/inifile"
    mongodb: "puppet/mongodb"
    postgresql: "puppetlabs/postgresql"
    rabbitmq: "puppet/rabbitmq"
    selinux: "puppet/selinux"
    nginx: "puppet/nginx"
    nodejs: "puppet/nodejs"
    recursive_file_permissions: "npwalker/recursive_file_permissions"
