# Fixtures file for puppet_spec_helper in the task: rake spec
fixtures:
  symlinks:
    st2: "#{source_dir}"
  forge_modules:
    httpauth: "jamtur01/httpauth"
    stdlib: "puppetlabs/stdlib"
    staging: "puppet/staging"
    apt: "puppetlabs/apt"
    concat: "puppetlabs/concat"
    wget: "puppet/wget"
    sudo: "saz/sudo"
    python: "puppet/python"
    gcc: "puppetlabs/gcc"
    inifile: "puppetlabs/inifile"
    mongodb: "puppet/mongodb"
    postgresql: "puppetlabs/postgresql"
    rabbitmq: "puppet/rabbitmq"
    epel: "stahnma/epel"
    packagecloud: "computology/packagecloud"
    selinux: "puppet/selinux"
    nginx: "puppet/nginx"
    nodejs: "puppet/nodejs"
