# Fixtures file for puppet_spec_helper in the task: rake spec
fixtures:
  symlinks:
    st2: "#{source_dir}"
  forge_modules:
    apt: "puppetlabs/apt"
    concat: "puppetlabs/concat"
    stdlib: "puppetlabs/stdlib"
    httpauth: "jamtur01/httpauth"
    staging: "nanliu/staging"
    git: "maestrodev/git"
    wget: "maestrodev/wget"
    sudo: "saz/sudo"
    python: "stankevich/python"
    gcc: "puppetlabs/gcc"
    inifile: "puppetlabs/inifile"
    mongodb: "puppetlabs/mongodb"
    postgresql: "puppetlabs/postgresql"
    rabbitmq: "puppetlabs/rabbitmq"
    epel: "stahnma/epel"
    facter: "ghoneycutt/facter"
    packagecloud: "computology/packagecloud"
    selinux: "puppet/selinux"
    nginx: "puppet/nginx"
    nodejs: "puppet/nodejs"
