---
driver:
  name: docker
  privileged: true
  use_sudo: false
  require_chef_omnibus: false

transport:
  name: sftp

provisioner:
  # in the container, run: puppet apply
  name: puppet_apply
  # manifest to execute
  manifest: test/fullinstall.pp
  # unused, but required
  modules_path: ./modules
  # don't have kitchen-puppet install chef by default
  require_chef_for_busser: false
  # don't have kitchen-puppet install puppet by default (done in Dockerfile)
  require_puppet_collections: false
  # no longer resolve with librarian-puppet because of dependency hell
  resolve_with_librarian_puppet: false
  # use r10k for installing dependencies so we have the explicitly installed
  # and avoid ordering problems and random minor version clashes
  resolve_with_r10k: true
  # If you do not enable puppet_detailed_exitcodes, the provisioner only failes
  # if the manifest can not be compiled.
  puppet_detailed_exitcodes: true
  # Exit code details:
  # https://github.com/neillturner/kitchen-puppet/blob/master/provisioner_options.md#checking-puppet-apply-success-with-puppet_detailed_exitcodes
  #   0: The run succeeded with no changes or failures; the system was already in the desired state.
  #   1: The run failed, or wasn't attempted due to another run already in progress.
  #   2: The run succeeded, and some resources were changed.
  #   4: The run succeeded, and some resources failed.
  #   6: The run succeeded, and included both changes and failures.
  puppet_whitelist_exit_code:
    - 0
    - 2

platforms:

  # CentOS6 with sysV init - Puppet 5
  - name: centos6-puppet5
    driver:
      platform: centos
      dockerfile: build/centos6-puppet5/Dockerfile.kitchen
      run_command: /usr/sbin/sshd -D
    provisioner:
      puppetfile_path: build/centos6-puppet5/Puppetfile

  # CentOS6 with sysV init - Puppet 6
  - name: centos6-puppet6
    driver:
      platform: centos
      dockerfile: build/centos6-puppet6/Dockerfile.kitchen
      run_command: /usr/sbin/sshd -D
    provisioner:
      puppetfile_path: build/centos6-puppet6/Puppetfile

  # CentOS7 with Systemd - Puppet 5
  - name: centos7-puppet5
    driver:
      platform: centos
      dockerfile: build/centos7-puppet5/Dockerfile.kitchen
      run_command: /sbin/init
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
    provisioner:
      puppetfile_path: build/centos7-puppet5/Puppetfile

  # CentOS7 with Systemd - Puppet 6
  - name: centos7-puppet6
    driver:
      platform: centos
      dockerfile: build/centos7-puppet6/Dockerfile.kitchen
      run_command: /sbin/init
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
    provisioner:
      puppetfile_path: build/centos7-puppet6/Puppetfile

  # Ubuntu Trusty with Upstart - Puppet 5
  - name: ubuntu14-puppet5
    driver:
      platform: ubuntu
      dockerfile: build/ubuntu14-puppet5/Dockerfile.kitchen
      disable_upstart: false
      run_command: /sbin/init
    provisioner:
      puppetfile_path: build/ubuntu14-puppet5/Puppetfile
      # Due to issues with running apt-get during 'docker build' on Ubuntu 14,
      # we need to install Puppet once the container has started.
      # Good news, kitchen-puppet supports this with the following commands:
      require_puppet_omnibus: true
      require_puppet_collections: true
      require_puppet_repo: false
      puppet_omnibus_url: https://raw.githubusercontent.com/petems/puppet-install-shell/master/install_puppet_5_agent.sh

  # Ubuntu Trusty with Upstart - Puppet 6
  - name: ubuntu14-puppet6
    driver:
      platform: ubuntu
      dockerfile: build/ubuntu14-puppet6/Dockerfile.kitchen
      disable_upstart: false
      run_command: /sbin/init
    provisioner:
      puppetfile_path: build/ubuntu14-puppet6/Puppetfile
      # Due to issues with running apt-get during 'docker build' on Ubuntu 14,
      # we need to install Puppet once the container has started.
      # Good news, kitchen-puppet supports this with the following commands:
      require_puppet_omnibus: true
      require_puppet_collections: true
      require_puppet_repo: false
      puppet_omnibus_url: https://raw.githubusercontent.com/nmaludy/puppet-install-shell/master/install_puppet_6_agent.sh

  # Ubuntu Xenial with Systemd - Puppet 5
  - name: ubuntu16-puppet5
    driver:
      platform: ubuntu
      dockerfile: build/ubuntu16-puppet5/Dockerfile.kitchen
      run_command: /sbin/init
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
    provisioner:
      puppetfile_path: build/ubuntu16-puppet5/Puppetfile

  # Ubuntu Xenial with Systemd - Puppet 6
  - name: ubuntu16-puppet6
    driver:
      platform: ubuntu
      dockerfile: build/ubuntu16-puppet6/Dockerfile.kitchen
      run_command: /sbin/init
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
    provisioner:
      puppetfile_path: build/ubuntu16-puppet6/Puppetfile

suites:
  - name: default

verifier:
  name: inspec
  sudo: true
  # by default `sudo` doesn't set many of the environment variables.
  # we need to tell sudo to set the $HOME env var to /root.
  # this way it picks up ~/.st2/config for the root user, configured by Puppet
  # this ~/.st2/config contains auth credentials to test out st2 comamnds
  # via inspec
  sudo_options: "HOME=/root -u root"
  inspec_tests:
    - path: test/integration/stackstorm
