---
sudo: required
dist: trusty
services: docker

branches:
  except:
  - gh-pages

language: ruby
bundler_args: --without rake

# TODO install modules as part of kitchen build (using librarian puppet
#install:
#  - if [[ -n $DISTRO ]]; then r10k puppetfile install -v --moduledir=/tmp/modules --puppetfile=docs/Puppetfile; else echo "Not running r10k because DISTRO is not set"; fi

script:
  - docker build -t stackstorm/puppet-st2-$DISTRO -f $BUILD_PATH/Dockerfile .
  - docker run -dit --name stackstorm-puppet-st2-$DISTRO stackstorm/puppet-st2-$DISTRO
  - docker exec stackstorm-puppet-st2-$DISTRO bash -c "bundle exec rake validate"
  - docker exec stackstorm-puppet-st2-$DISTRO bash -c "bundle exec rake lint"
  - docker exec stackstorm-puppet-st2-$DISTRO bash -c "bundle exec rake spec SPEC_OPTS='--format documentation'"
  - if [[ -n $DISTRO ]]; then kitchen test ${DISTRO}; else echo "Not running kitchenci because DISTRO is not set"; fi


matrix:
  fast_finish: true
  include:
    - rvm: 2.4
      gemfile: build/kitchen/Gemfile
      env:
        - BUILD_NAME="RHEL/CentOS 6"
        - DISTRO=centos-6
        - BUILD_PATH="build/centos6"
    - rvm: 2.4
      gemfile: build/kitchen/Gemfile
      env:
        - BUILD_NAME="RHEL/CentOS 7"
        - DISTRO=centos-7
        - BUILD_PATH="build/centos7"
    - rvm: 2.4
      gemfile: build/kitchen/Gemfile
      env:
        - BUILD_NAME="Ubuntu 14"
        - DISTRO=ubuntu-14
        - BUILD_PATH="build/ubuntu14"
    - rvm: 2.4
      gemfile: build/kitchen/Gemfile
      env:
        - BUILD_NAME="Ubuntu 16"
        - DISTRO=ubuntu-16
        - BUILD_PATH="build/ubuntu16"
    - rvm: 2.4
      gemfile: build/kitchen/Gemfile
      env:
        - BUILD_NAME="Puppet 4 (generic)"
        - BUILD_PATH="build/puppet4"
    - rvm: 2.4
      gemfile: build/kitchen/Gemfile
      env:
        - BUILD_NAME="Puppet 5 (generic)"
        - BUILD_PATH="build/puppet5"

# Note: disabling notifications during initial kitchen ci testing
# notifications:
#   # Post build failures to '#puppet' channel in 'stackstorm-community' Slack
#   slack:
#     rooms:
#       - secure: SJ0wpsrrq7oYeepFawJs2iSuKLpWr6aoyWgP+fTPLq8tcZGuIUKJSLM+1FZddYE08QvykO1E0jyeqBrTyvFc7EwsW6vD5bpFYGtVMSMJJIgk76UEhmXbqtTJTjfjYT7/7RDnWlEGXXS7icIZSkEP1moz34fXEDbXKzCpFtqZkAo=
#     on_pull_requests: false
#     on_success: change # default: always
#     on_failure: always # default: always
