---
os: linux
dist: bionic
services: docker
language: ruby
cache: bundler
before_install:
  - if [ $BUNDLER_VERSION ]; then
      gem install -v $BUNDLER_VERSION bundler --no-rdoc --no-ri;
    fi
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
bundler_args: --without system_tests

# execute all commands in a single script with 'set -e' at the top
# otherwise if you specify >1 command here, travis will try to run them
# all and if one fails it will ignore the failure and go onto the next
script:
  - build/scripts/ci.sh

stages:
  - test
  - if: tag =~ ^v\d
    name: deploy

jobs:
  fast_finish: true
  include:
    - name: "Unit Testing - Puppet 5"
      stage: test
      rvm: 2.4
      # use default Gemfile in repo root (from PDK)
      env:
        - UNIT_TEST="true"
        - PUPPET_GEM_VERSION="~> 5.0"
        - CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop parallel_spec"
    - name: "Unit Testing - Puppet 6"
      stage: test
      rvm: 2.5
      # use default Gemfile in repo root (from PDK)
      env:
        - UNIT_TEST="true"
        - PUPPET_GEM_VERSION="~> 6.0"
        - CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop parallel_spec"
    - name: "Unit Testing - Bolt Tasks Python 2.7"
      stage: test
      language: python
      python: 2.7
      cache: pip
      before_install:
        - echo 'no bundler needed here'
      script:
        - make python2
    - name: "Unit Testing - Bolt Tasks Python 3.6"
      stage: test
      language: python
      python: 3.6
      cache: pip
      before_install:
        - echo 'no bundler needed here'
      script:
        - make python3
    - name: "Documentation Testing"
      stage: test
      rvm: 2.5
      # use default Gemfile in repo root (from PDK)
      env:
        - DOCS_TEST="true"
        - PUPPET_GEM_VERSION="~> 6.0"
    - name: "RHEL/CentOS 6 - Puppet 5"
      stage: test
      rvm: 2.5
      gemfile: build/kitchen/Gemfile
      env:
        - TEST_NAME="centos6-puppet5"
    - name: "RHEL/CentOS 6 - Puppet 6"
      stage: test
      rvm: 2.5
      gemfile: build/kitchen/Gemfile
      env:
        - TEST_NAME="centos6-puppet6"
    - name: "RHEL/CentOS 7 - Puppet 5"
      stage: test
      rvm: 2.5
      gemfile: build/kitchen/Gemfile
      env:
        - TEST_NAME="centos7-puppet5"
    - name: "RHEL/CentOS 7 - Puppet 6"
      stage: test
      rvm: 2.5
      gemfile: build/kitchen/Gemfile
      env:
        - TEST_NAME="centos7-puppet6"
    - name: "Ubuntu 16 - Puppet 5"
      stage: test
      rvm: 2.5
      gemfile: build/kitchen/Gemfile
      env:
        - TEST_NAME="ubuntu16-puppet5"
    - name: "Ubuntu 16 - Puppet 6"
      stage: test
      rvm: 2.5
      gemfile: build/kitchen/Gemfile
      env:
        - TEST_NAME="ubuntu16-puppet6"
    - name: "Ubuntu 18 - Puppet 5"
      stage: test
      rvm: 2.5
      gemfile: build/kitchen/Gemfile
      env:
        - TEST_NAME="ubuntu18-puppet5"
    - name: "Ubuntu 18 - Puppet 6"
      stage: test
      rvm: 2.5
      gemfile: build/kitchen/Gemfile
      env:
        - TEST_NAME="ubuntu18-puppet6"
    - name: "Deploy to Forge"
      stage: deploy
      env: DEPLOY_TO_FORGE=yes
      script:
        # override the script so travis just goes on to do the deploy
        - echo "Deploying to Forge..."

notifications:
  # Post build failures to '#puppet' channel in 'stackstorm-community' Slack
  slack:
    rooms:
      - secure: SJ0wpsrrq7oYeepFawJs2iSuKLpWr6aoyWgP+fTPLq8tcZGuIUKJSLM+1FZddYE08QvykO1E0jyeqBrTyvFc7EwsW6vD5bpFYGtVMSMJJIgk76UEhmXbqtTJTjfjYT7/7RDnWlEGXXS7icIZSkEP1moz34fXEDbXKzCpFtqZkAo=
    on_pull_requests: false
    on_success: change # default: always
    on_failure: always # default: always

# restrict build so our tagging deploys work properly
branches:
  only:
  - master
  - /^v\d/

# deploy to forge when tagged with a new release
deploy:
  provider: puppetforge
  username: stackstorm
  password:
    secure: "Em3vLHZA/asZiNHN5FO9DQAGLaQYEn9zCoDrkcOJUROFViY8luFvJ6necCnFQEGtC3kHXwoFpD05oCOxeVDm8NNzIbjFKPT7B4/wBndshp4pataxQNgnz8zw3Jufgih8p7nxf/ikugUiQKOiqKlp2U6QEGi5oVEQ5UpKx8KvhNg="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
