---
sudo: required
dist: trusty
services: docker

branches:
  except:
  - gh-pages

language: ruby
bundler_args: --without rake

install:
  - ln -s ${GEMFILE_LOCK} Gemfile.lock
  - bundle install --without rake
  - if [[ -n $DISTRO ]]; then r10k puppetfile install -v --moduledir=/tmp/modules --puppetfile=docs/Puppetfile; else echo "Not running r10k because DISTRO is not set"; fi

script:
  - facter
  - bundle exec rake validate 
  - bundle exec rake lint
  - bundle exec rake spec SPEC_OPTS='--format documentation'
  - if [[ -n $DISTRO ]]; then kitchen test ${DISTRO}; else echo "Not running kitchenci because DISTRO is not set"; fi


matrix:
  fast_finish: true
  include:
    - rvm: 1.8.7
      env:
        - BUILD_NAME="RHEL 6"
        - PUPPET_VERSION="~> 3.0"
        - GEMFILE_LOCK=".travis-gemfile/Gemfile.lock.rhel6"
        - TEST_KITCHEN_ENABLED="false"
        - R10K_VERSION="~> 1.0"
        - PUPPETLABS_SPEC_HELPER_VERSION="~> 1.2.0"
        - PUPPET_BLACKSMITH_VERSION="~> 3.1.0"
    - rvm: 2.0.0
      env:
        - BUILD_NAME="RHEL 7"
        - DISTRO=centos-7
        - PUPPET_VERSION="~> 3.0"
        - GEMFILE_LOCK=".travis-gemfile/Gemfile.lock.rhel7"
    - rvm: 1.9.3
      env:
        - BUILD_NAME="Ubuntu 14"
        - DISTRO=ubuntu-14
        - PUPPET_VERSION="~> 3.0"
        - GEMFILE_LOCK=".travis-gemfile/Gemfile.lock.ubuntu14"
        # Need to lock kitchen sync version due to new versions not being
        # compatible  with the version of ruby installed on ubuntu14
        - KITCHEN_SYNC_VERSION="2.1.0"
    # Can't run our unittests against default puppet version on Ubuntu 16
    # because it ships with a brand new version of Ruby (2.3.x) and an old
    # version of puppet (3.8.5) that is not compatible with new versions
    # of Ruby that are needed for the unit tests. This is only a unit testing
    # deficiency, the runtime component of 3.8.5 works just fine with ruby 2.3
    # for using this module.
    - rvm: 2.3.1
      env:
        - BUILD_NAME="Ubuntu 16"
        - DISTRO=ubuntu-16
        - PUPPET_VERSION="~> 4.0"
        - GEMFILE_LOCK=".travis-gemfile/Gemfile.lock.ubuntu16"
    - rvm: 2.1.10
      env:
        - BUILD_NAME="Puppet 4 (generic)"
        - PUPPET_VERSION="~> 4.0"
        - GEMFILE_LOCK=".travis-gemfile/Gemfile.lock.puppet4"
        - TEST_KITCHEN_ENABLED="false"
    - rvm: 2.4.2
      env:
        - BUILD_NAME="Puppet 5 (generic)"
        - PUPPET_VERSION="~> 5.0"
        - GEMFILE_LOCK=".travis-gemfile/Gemfile.lock.puppet5"
        - TEST_KITCHEN_ENABLED="false"

# Note: disabling notifications during initial kitchen ci testing
# notifications:
#   # Post build failures to '#puppet' channel in 'stackstorm-community' Slack
#   slack:
#     rooms:
#       - secure: SJ0wpsrrq7oYeepFawJs2iSuKLpWr6aoyWgP+fTPLq8tcZGuIUKJSLM+1FZddYE08QvykO1E0jyeqBrTyvFc7EwsW6vD5bpFYGtVMSMJJIgk76UEhmXbqtTJTjfjYT7/7RDnWlEGXXS7icIZSkEP1moz34fXEDbXKzCpFtqZkAo=
#     on_pull_requests: false
#     on_success: change # default: always
#     on_failure: always # default: always
