# @summary Profile to install and configure chatops for st2
#
# @note This class doesn't need to be invoked directly, instead it's best to customize
#       it through the main +st2+ class
#
# @param version
#    Version of the st2chatops package to install
# @param hubot_log_level
#    Hubot log level
# @param hubot_express_port
#    Express port hubot listens to
# @param cert_reject_unauth
#    Set to 1 when using self signed certs
# @param hubot_name
#    Name of the bot in chat. Should be properly quoted if it has special characters,
#    example: '"MyBot!"'
# @param hubot_alias
#    Character to trigger the bot at the beginning of a message. Must be properly
#    quoted of it's a special character, example: "'!'"
# @param npm_packages
#    NodeJS packages to be installed (usually a hubot adapter)
# @param adapter_config
#    Configuration parameters for Hubot adapter (hash)
# @param api_key
#    API key generated by <code>st2 apikey create</code> that hubot will use to post data back
#    to StackStorm.
# @param st2_hostname
#    Hostname of the StackStorm instance that chatops will connect to for API and Auth.
#    If unspecified it will use the default in <code>/opt/stackstorm/chatops/st2chatops.env</code>
# @param auth_username
#    StackStorm auth Username for ChatOps to communicate back with StackStorm.
#    Used if +api_key+ is not specified (optional)
# @param auth_password
#    StackStorm auth Password for ChatOps to communicate back with StackStorm.
#    Used if +api_key+ is not specified (optional)
# @param chatops_packages
#    Array of packages to install for chatops
# @param conf_dir
#    Directory where chatops configuration files are stored
# @param global_env_file
#    Path to the global environment file
# @param base_url
#    URL of the StackStorm instance that chatops will connect to for API and Auth.
# @param services
#    Array of services to manage
#
# @example Basic Usage
#   class { 'st2':
#     chatops_hubot_name => '"@RosieRobot"',
#     chatops_api_key    => '"xxxxyyyyy123abc"',
#     chatops_adapter    => {
#       hubot-adapter => {
#         package => 'hubot-rocketchat',
#         source  => 'git+ssh://git@git.company.com:npm/hubot-rocketchat#master',
#       },
#     },
#     chatops_adapter_conf => {
#       HUBOT_ADAPTER        => 'rocketchat',
#       ROCKETCHAT_URL       => 'https://chat.company.com',
#       ROCKETCHAT_ROOM      => 'stackstorm',
#       LISTEN_ON_ALL_PUBLIC => 'true',
#       ROCKETCHAT_USER      => 'st2',
#       ROCKETCHAT_PASSWORD  => 'secret123',
#       ROCKETCHAT_AUTH      => 'password',
#       RESPOND_TO_DM        => 'true',
#     },
#   }
#
class st2::profile::chatops (
  Hash                     $adapter_config       = $st2::chatops_adapter_conf,
  Optional[String]         $api_key              = $st2::chatops_api_key,
  String                   $auth_password        = $st2::cli_password,
  String                   $auth_username        = $st2::cli_username,
  Stdlib::HTTPUrl          $base_url             = $st2::chatops_base_url,
  Array[String[1]]         $chatops_packages     = ['st2chatops'],
  Stdlib::Absolutepath     $conf_dir             = $st2::chatops_conf_dir,
  Stdlib::Absolutepath     $global_env_file      = $st2::chatops_global_conf,
  String                   $hubot_alias          = $st2::chatops_hubot_alias,
  Stdlib::Port             $hubot_express_port   = 8081,
  String                   $hubot_log_level      = $st2::chatops_hubot_log_level,
  String                   $hubot_name           = $st2::chatops_hubot_name,
  Hash                     $npm_packages         = $st2::chatops_adapter,
  Array[String[1]]         $services             = ['st2chatops'],
  Stdlib::Host             $st2_hostname         = $st2::chatops_st2_hostname,
  Enum['0','1']            $cert_reject_unauth   = $st2::chatops_cert_reject_unauth,
  St2::Ensure              $version              = $st2::version,
) inherits st2 {
  #
  ## Local variables
  $_chatops_env_file = "${conf_dir}/st2chatops.env"

  ########################################
  ## Packages
  ensure_packages([$chatops_packages],
    {
      'ensure' => $version,
      'tag'    => ['st2::packages', 'st2::chatops::packages'],
    }
  )

  ########################################
  ## Config
  file { $global_env_file:
    ensure  => file,
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    content => epp('st2/etc/sysconfig/st2chatops.epp',
      {
        st2_hostname  => $st2_hostname,
        api_url       => "${base_url}/api",
        auth_url      => "${base_url}/auth",
        api_key       => $api_key,
        auth_username => $auth_username,
        auth_password => $auth_password,
        web_url       => "${base_url}/",
      }
    ),
    tag     => 'st2::chatops::config',
  }

  file { $_chatops_env_file:
    ensure  => file,
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    content => epp('st2/opt/stackstorm/chatops/st2chatops.env.epp',
      {
        adapter_config     => $adapter_config,
        cert_reject_unauth => $cert_reject_unauth,
        hubot_alias        => $hubot_alias,
        hubot_express_port => $hubot_express_port,
        hubot_log_level    => $hubot_log_level,
        hubot_name         => $hubot_name,
        st2_hostname       => $st2_hostname,
      }
    ),
    tag     => 'st2::chatops::config',
  }

  ########################################
  ## Additional nodejs packages
  include st2::profile::nodejs

  $npm_package_defaults = {
    ensure  => present,
    target  => $conf_dir,
    require => Class['St2::Profile::Nodejs'],
    tag     => 'st2::chatops::npm_package',
  }

  create_resources('nodejs::npm', $npm_packages, $npm_package_defaults)

  ########################################
  ## Services
  service { $services:
    ensure => 'running',
    enable => true,
    tag    => 'st2::chatops::service',
  }

  ########################################
  ## Dependencies
  Package<| tag == 'st2::chatops::packages' |>
  -> File<| tag == 'st2::chatops::config' |>
  ~> Service<| tag == 'st2::chatops::service' |> # notify to force a refresh

  # st2api, st2auth, etc need to be running in order for st2chatops to work
  Service<| tag == 'st2::service' |>
  -> Service<| tag == 'st2::chatops::service' |>

  Nodejs::Npm<| tag == 'st2::chatops::npm_package' |>
  -> Service<| tag == 'st2::chatops::service' |>
}
